### PR TITLE
Add support for Mid-State Technical College

### LINKED ISSUE #398: [New University]: Mid-State Technical College
### University name

Mid-State Technical College

### University abbreviation

MSTC

### University country

United States

### URL of university Blackboard instance

https://mstc.blackboard.com

### URL after logging in

https://mstc.blackboard.com/ultra/

### University network information

Name: WISCNET-BLOCK1
Description: missing
Country:

### Valid Blackboard data sources (optional)

_No response_

### Anything else to add?

I created this issue because the first one had the wrong url format

### License

- [X] I agree to follow this project's License

### PR DESCRIPTION
**Pull request by sanjacob**
Created on behalf of @lint-os
Closes #398

### CODE REVIEW

**Comment by lint-os** [comment]
If the url is missing the https:// prefix, the issue creation doesn't work fyi

**Comment by lint-os** [comment]
I can log in, but the app does not detect that it is

**Comment by sanjacob** [comment]
@lint-os can you edit the URL after logging in to be: "https://mstc.blackboard.com/ultra/"? (Without the institution-page bit) 

Just edit your issue #398 rather than creating a new one. Maybe that will solve it.

**Comment by lint-os** [comment]
It now has logged in properly, waiting to see if it syncs

**Comment by lint-os** [comment]
Yes it is. Perfect!
This should be ready to merge

**Comment by lint-os** [comment]
Huh, got a new error from Windows: 
Download error
Traceback (most recent call last):
  File "pathlib.py", line 1116, in mkdir
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\Me\\Documents\\dl4\\2024\\Orientation for Courses Using Blackboard Ultra\\Resources for Technology Assistance, Time Management, Study Skills, and Motivation (WIP)\\Time Management Ideas\\10 Time Management Skills and Techniques for Students (article)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "blackboard_sync\sync.py", line 153, in download
  File "blackboard_sync\download.py", line 104, in download
  File "blackboard_sync\content\course.py", line 42, in write
  File "blackboard_sync\content\content.py", line 67, in write
  File "blackboard_sync\content\folder.py", line 29, in write
  File "blackboard_sync\content\content.py", line 67, in write
  File "blackboard_sync\content\folder.py", line 29, in write
  File "blackboard_sync\content\content.py", line 65, in write
  File "pathlib.py", line 1121, in mkdir
  File "pathlib.py", line 1116, in mkdir
FileNotFoundError: [WinError 206] The filename or extension is too long: 'C:\\Users\\Me\\Documents\\dl4\\2024\\Orientation for Courses Using Blackboard Ultra\\Resources for Technology Assistance, Time Management, Study Skills, and Motivation (WIP)\\Time Management Ideas\\10 Time Management Skills and Techniques for Students (article)'

I tried to fix it with regedit by navigating to Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem and edit LongPathsEnabled and set value from 0 to 1, but it didn't work. I try to set the folder on C:/

**Comment by lint-os** [comment]
No, that is still a problem.

**Comment by lint-os** [comment]
added #401

**Pull request merged**
