### PR TITLE
Add support for Hong Kong Community College

### PR DESCRIPTION
**Pull request by Benson-mk**
Tested

### CODE REVIEW

**Comment by Benson-mk** [comment]
update: occur the same error as #110 
it try fetching a child course (in the sample is 2023-1 programming course (Group 101A)) that is not available for me
and it starts an error loop
```
Fetching course
<2023-1 programming course (Group 101A)> - <2023-1 programming course (Group 101A)>
Writing to C:\Users\benson\Documents\BlackboardSync\downlaods\2023\2023-1 language course\...\.pdf
Exception in sync thread
Traceback (most recent call last):
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\sync.py", line 173, in _sync_task
    job_start_time = self._download.download()
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\download.py", line 248, in download
    course_contents = self._sess.fetch_contents(course_id=course.id)
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\blackboard\api.py", line 114, in get_wrapper
    raise ValueError('Server responded with an error code')
ValueError: Server responded with an error code
User session expired
Stopping sync thread
Logged in successfully
Starting sync thread
Fetching user memberships
Writing to C:\Users\benson\Documents\BlackboardSync\downlaods\2023\2023-1 language course\...\.pdf
...

Fetching course
<2023-1 programming course (Group 101A)> - <2023-1 programming course (Group 101A)>
Exception in sync thread
Traceback (most recent call last):
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\sync.py", line 173, in _sync_task
    job_start_time = self._download.download()
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\download.py", line 248, in download
    course_contents = self._sess.fetch_contents(course_id=course.id)
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\blackboard\api.py", line 114, in get_wrapper
    raise ValueError('Server responded with an error code')
ValueError: Server responded with an error code
User session expired
Stopping sync thread
Logged in successfully
Starting sync thread
Fetching user memberships
Writing to C:\Users\benson\Documents\BlackboardSync\downlaods\2023\2023-1 history course\...\.pdf
...

Fetching course
<2023-1 programming course (Group 101A)> - <2023-1 programming course (Group 101A)>
Writing to C:\Users\benson\Documents\BlackboardSync\downlaods\2023\2023-1 programming course (Centralized Group)\ Teaching Plan.pdf
Exception in sync thread
Traceback (most recent call last):
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\sync.py", line 173, in _sync_task
    job_start_time = self._download.download()
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\download.py", line 248, in download
    course_contents = self._sess.fetch_contents(course_id=course.id)
  File "C:\Users\benson\Documents\BlackboardSync\blackboard_sync\blackboard\api.py", line 114, in get_wrapper
    raise ValueError('Server responded with an error code')
ValueError: Server responded with an error code
User session expired
Stopping sync thread
Logged in successfully
Starting sync thread
Writing to C:\Users\benson\Documents\BlackboardSync\downlaods\2023\2023-1 programming course (Centralized Group)\ Guide 2023-2024.pdf
...
```

**Comment by sanjacob** [comment]
I'll implement a fix as soon as I have some extra time.

**Comment by sanjacob** [comment]
@Benson-mk can you add a print statement in api.py and tell me which error code you get?

**Comment by sanjacob** [comment]
Right below this statement:

```python
elif 'status' in response:
    print(response)
    ...
```

**Comment by sanjacob** [comment]
@Benson-mk I have now merged code that will check that a course or content is available before attempting download. However, I have also merged plenty of other code, so I have no idea how things might be for you. But I suggest you clone the latest commit and report back with any error messages you see (ideally none).

**Comment by sanjacob** [comment]
@Benson-mk should work fine now, try the main branch as of now

**Pull request merged**
