### PR TITLE
Add support for the University of Aberdeen

### PR DESCRIPTION
**Pull request by cbraidwood**
Added details for the University of Aberdeen to the universities.json file.

### CODE REVIEW

**Comment by sanjacob** [comment]
Have you tried this yourself? Can you confirm it works as expected?

**Comment by cbraidwood** [comment]
The correct login website appears in the window, and I am able to log in. After logging in, the window minimizes to the system tray with a notification that it is downloading. However, it hangs with the following message:

```
$ python -m blackboard_sync
Loading preexisting configuration
js: New Relic: A problem occurred when starting up session manager. This page will not start or extend any session.
js: ChunkLoadError: Loading chunk 75 failed.
(error: https://js-agent.newrelic.com/nr-rum-1.249.0.min.js)
js: New Relic: A problem occurred when starting up session manager. This page will not start or extend any session.
js: ChunkLoadError: Loading chunk 75 failed.
(error: https://js-agent.newrelic.com/nr-rum-1.249.0.min.js)
js: New Relic: A problem occurred when starting up session manager. This page will not start or extend any session.
js: ChunkLoadError: Loading chunk 75 failed.
(error: https://js-agent.newrelic.com/nr-rum-1.249.0.min.js)
js: New Relic: Downloading runtime APIs failed...
js: New Relic: Downloading and initializing page_view_event failed...
js: ChunkLoadError: Loading chunk 75 failed.
(error: https://js-agent.newrelic.com/nr-rum-1.249.0.min.js)
js: New Relic: Downloading and initializing page_view_timing failed...
js: ChunkLoadError: Loading chunk 75 failed.
(error: https://js-agent.newrelic.com/nr-rum-1.249.0.min.js)
js: New Relic: Downloading and initializing metrics failed...
js: ChunkLoadError: Loading chunk 75 failed.
(error: https://js-agent.newrelic.com/nr-rum-1.249.0.min.js)
js: Attempting to get paged collection at /public/v1/lti/placements without a filter, this might be a performance issue.
js: Invalid 'X-Frame-Options' header encountered when loading 'https://developer.blackboard.com/': '' is not a recognized directive. The header will be ignored.
js: Received subscription to invalid event type basenav:register
js: Invalid class name: svg-icon
js: Invalid class name: medium-icon
js: Invalid class name: default
js: Invalid class name: svg-icon
js: Invalid class name: medium-icon
js: Invalid class name: default
Logged in successfully
Starting sync thread
Exception in thread Thread-1 (_sync_task):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/charlie/code/testblackboard/BlackboardSync/blackboard_sync/sync.py", line 164, in _sync_task
    self._download = BlackboardDownload(user_session,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/charlie/code/testblackboard/BlackboardSync/blackboard_sync/download.py", line 68, in __init__
    self._user_id = sess.username
                    ^^^^^^^^^^^^^
  File "/home/charlie/code/testblackboard/BlackboardSync/blackboard_sync/blackboard/api.py", line 126, in username
    username = self.fetch_users(user_id='me')['userName']
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'userName'
```

**Note:** when I used pipenv to run, the web viewer did not work (for any university page)

**Comment by sanjacob** [comment]
Try visiting this URL in the browser while logged in:  https://abdn.blackboard.com/learn/api/public/v1/users/me

You should see a json response with your username. If that's the case then it is most likely that the session is somehow not getting preserved after logging in (or the login process is not complete). As for why you can't make it work with pipenv I don't really know but one user reported having to deal with the pyqt sandbox before in order to be able to open the loginwebview. But he did not elaborate.

**Comment by sanjacob** [comment]
Also, please check your browser's js log output when you do the username check, just to make sure the errors that came up in the app are also coming up in the browser and are therefore not to blame.

**Comment by cbraidwood** [comment]
There is no userId / userName field with the same username login name when I visit that URL while logged into blackboard, only id, uuid, studentId etc. 

The js log on browser returns the same errors but I don't see the ChunkLoadError.

**Comment by sanjacob** [comment]
Your university's installation of blackboard must be configured in a different way than usual. I will need to make changes to the project to support edge cases like this. Usually, the server responds with a userName, so the program assumes that is the case. I think the studentId/id fields can be treated the same but I will need some time to fix it before officially supporting your university. I am planning to make the blackboard module a dependency instead of including it in this project, so if you are planning on making a PR you will have to do so at https://github.com/sanjacob/bblearn

**Comment by ziyuanding** [comment]
Exactly the same issue for The University of Western Australia(UWA), replacing "userName" with "id" would be a temp solution.
image

**Pull request merged**
